### ISSUE TITLE
Thumbnails are not copied to _site

### ISSUE THREAD

**Issue by Schrank** [abpaudel/jekyll-thumbnail-img#2]
Hi @abpaudel!

Thanks for this lovely plugin! It took a moment for me as a PHP guy to set it up, but now it is working fine locally. And by fine I mean I run the build, the thumbnails are generated but not copied over to _site.
Then I run _build again and they are.

It seems they are generated too late and I guess they need to be copied to _site, which if I understand correctly happens if they are added to static_files property/variable (not sure how it is called in Ruby :-) )

**Comment by abpaudel** [comment]
This is a known issue. The ideal solution is to write the thumbnail images directly into the `_site` directory and not in the local directory so that you'll not have to commit the thumbnail images while deploying the site. This is feature is next in my TODO list for this plugin. Feel free to send a PR if you'd like to contribute on this.
